name: rojgaar
description: A new Flutter project

publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1  # Ensure latest stable version
  firebase_auth: 5.4.1   # Ensure latest stable version
  cloud_firestore: ^5.6.2 # Ensure latest stable version
  firebase_auth_web: 5.13.7 # Explicitly include web version of firebase_auth
  speech_to_text: 7.0.0
  intl: 0.20.2
  firebase_storage: ^12.4.1
  image_picker: 1.1.2
  url_launcher: 6.3.1
  flutter_neumorphic: 3.2.0
  getwidget: 5.0.0
  flutter_launcher_icons: 0.14.3

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

